server:
  port: 18023

# 配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: cn.luoye.game.MonopolyGame.**.entity
  configuration:
    map-underscore-to-camel-case: true

# 配置mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123456
    url: jdbc:mysql://localhost:3306/monopoly_game?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8

#配置redis
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 3000


upload_url:
  url: F:/testimage/
  ip: F:/

test: 123